[env]
TERM = "xterm-256color"

[window]
padding.x = 5
padding.y = 5
startup_mode = "Maximized"

decorations = "Full"
opacity = 1
blur = true

decorations_theme_variant = "Dark"

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 13.0

[keyboard]
bindings = [
{ key = "c", mods = "Control|Shift", action = "Copy" },
{ key = "v", mods = "Control|Shift", action = "Paste" },
# { key = "p", mods = "Shift", action = "ToggleFullscreen" },
]

